<?php

/**
 * Implements hook_theme().
 */
function google_ai_application_theme(
  $existing,
  $type,
  $theme,
  $path
) {
  $module_path = \Drupal::service('extension.list.module')->getPath('google_ai_application');

  return [

    'google_ai_application' => [
      'variables' => [
        'label' => NULL,
        'project_name' => NULL,
        'data_store_name' => NULL,
        'schema_name' => NULL,
        'location' => NULL,
        'branch_name' => NULL,
        'content_types' => NULL,
        'serving_config' => NULL,
        'total_nodes' => 0,
        'content_type_counts' => [],
      ],
      'template' => 'google-ai-application',
    ],

    'google_ai_application_search_form' => [
      'render element' => 'form',
      'template' => 'form--google-ai-application-search-form',
      'path' => $module_path . '/templates/form',
    ],

    'google_ai_application_page' => [
      'template' => 'google-ai-application-page',
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'cta_links' => [],
        'search_form' => [],
        'facet_form' => [],
        'search_query' => '',
        'results' => [],
        'footer_cards' => [],
      ],
    ],

  ];
}
