google_ai_application.view:
  route_name: entity.google_ai_application.canonical
  base_route: entity.google_ai_application.canonical
  title: 'View'

google_ai_application.edit:
  route_name: entity.google_ai_application.edit_form
  base_route: entity.google_ai_application.canonical
  title: 'Edit'

google_ai_application.create_application:
  route_name: google_ai_application.create_application_form
  base_route: entity.google_ai_application.canonical
  title: 'Create Application'

google_ai_application.schema:
  route_name: google_ai_application.schema_form
  base_route: entity.google_ai_application.canonical
  title: 'Schema'

google_ai_application.import:
  route_name: google_ai_application.import_form
  base_route: entity.google_ai_application.canonical
  title: 'Import'

google_ai_application.purge:
  route_name: google_ai_application.purge_form
  base_route: entity.google_ai_application.canonical
  title: 'Purge'

google_ai_application.search_component:
  route_name: google_ai_application.search_component_form
  base_route: entity.google_ai_application.canonical
  title: 'Search Component'
